In [1]:
# stupid bullshit things
import numpy as np
from statistics import variance as var

In [2]:
entries = [[1, 1],
          [1, 2],
          [1, 3],
          [1, 4],
          [1, 5]]
x = np.array(entries)
y = np.array([[2.5, 5.5, 6.0, 10.0, 10.5]])
y = y.transpose()

A = np.linalg.inv(np.matmul(x.transpose(), x))
thetaHat = np.matmul(np.matmul(A, x.transpose()), y)
thetaHat

array([[0.75],
       [2.05]])

In [3]:
H = np.matmul(np.matmul(x, A), x.transpose())
yHat = np.matmul(H, y)
yHat

array([[ 2.8 ],
       [ 4.85],
       [ 6.9 ],
       [ 8.95],
       [11.  ]])

In [4]:
e = np.matmul((np.identity(5) - H), y)
e

array([[-0.3 ],
       [ 0.65],
       [-0.9 ],
       [ 1.05],
       [-0.5 ]])

In [5]:
s = np.var(y.transpose())
C = var(y) * A
C

TypeError: can't convert type 'ndarray' to numerator/denominator

In [6]:
xnew = np.array([[1, 2.5],
                [1, 5.5]])
ynew = np.matmul(xnew, thetaHat)
ynew

array([[ 5.875],
       [12.025]])